#!/usr/bin/python

import rpm
import re
import tempfile
import shutil
import subprocess
import requests
import os
import sys
from filecmp import dircmp

REPO_SUBDIR="repo"

def report_diff(prefix, dcmp):

    must_review = False
    for name in dcmp.diff_files:
        print("~ ", os.path.join(prefix, name))
        must_review = True
    for name in dcmp.left_only:
        print("- ", os.path.join(prefix, name))
        must_review = True
    for name in dcmp.right_only:
        print("+ ", os.path.join(prefix, name))
        must_review = True
    for name, sub_dcmp in dcmp.subdirs.items():
        must_review_returned = report_diff(os.path.join(prefix, name), sub_dcmp)
        must_review = must_review or must_review_returned
    return must_review

def list_files(input):
    for fd, subfds, fns in os.walk(input):
       for fn in fns:
            yield os.path.join(fd, fn)

spec = rpm.spec(sys.argv[1])
vcs_re =  re.compile("^VCS:(.*)$")

uri = None
for line in spec.parsed.splitlines():
  r = vcs_re.match(line)
  if r:
    uri=r.group(1).strip()
    break

if not uri:
  exit(0)

uri_re = re.compile("([a-z]+)\\+([^#]+)#(.+)")
vcs_match = uri_re.match(uri)
if not vcs_match or len(vcs_match.groups()) < 3:
  print(f"URI is not in expected format [vcs]+URI#[tag]: {uri}")
  exit(1)

vcs = vcs_match.group(1)
repo_uri = vcs_match.group(2)
tag = vcs_match.group(3)

if vcs != "git":
  print("Only git is supported, but found: {vcs}")
  exit(0)

clonepath = tempfile.mkdtemp()

git_run = subprocess.run(["git", "-C", clonepath, "clone", repo_uri, "--branch", tag, REPO_SUBDIR], capture_output=True)

if git_run.returncode > 0:
  print(f"git clone exited with {git_run.returncode}: {git_run.stdout} \n {git_run.stderr}")
  exit(1)

tarurl,_,_ = next(reversed(spec.sources)) # TODO: cleanup, assuming first source0 is the tar.gz

tarfile = tempfile.mktemp()
r = requests.get(tarurl)

with open(tarfile, 'wb') as f:
    f.write(r.content)

extractpath = tempfile.mkdtemp()

tar_run = subprocess.run(["tar", "xf", tarfile, "-C", extractpath, "--strip-components=1"], capture_output=True)
if tar_run.returncode > 0:
  print(f"tar xf exited with {tar_run.returncode}: {tar_run.stdout} \n {tar_run.stderr}")
  exit(1)

dcmp = dircmp(os.path.join(clonepath, REPO_SUBDIR), extractpath)

print("-----Diff-----")
must_review = report_diff(".", dcmp)

print("-----Blobs----")

for fn in list_files(extractpath):
    out = subprocess.run(["file", "--mime-type", "--brief", fn], capture_output=True)
    rel_fn = fn[len(extractpath)+1:]
    if out.returncode > 0:
       print(f"error looking into {rel_fn}")
       must_review = True
    mime = out.stdout.decode("utf-8")
    if not mime.startswith("text/"):
       print(f"{mime} {rel_fn}")
       must_review = True

shutil.rmtree(clonepath)
os.remove(tarfile)
shutil.rmtree(extractpath)

if must_review:
   exit(2)
